"""empty message

Revision ID: 447e72510544
Revises: 96f110586c16
Create Date: 2025-05-31 13:31:11.576569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '447e72510544'
down_revision: Union[str, None] = '96f110586c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posttaglink',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.drop_table('poster')
    op.drop_table('userbase')
    op.drop_table('member')
    op.drop_constraint(op.f('authsession_user_id_fkey'), 'authsession', type_='foreignkey')
    op.create_foreign_key(None, 'authsession', 'user', ['user_id'], ['id'])
    op.add_column('comment', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('comment', sa.Column('parend_id', sa.Uuid(), nullable=False))
    op.add_column('comment', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('comment', sa.Column('post_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('comment_member_id_fkey'), 'comment', type_='foreignkey')
    op.drop_constraint(op.f('comment_poster_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'comment', ['parend_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_column('comment', 'poster_id')
    op.drop_column('comment', 'member_id')
    op.drop_constraint(op.f('loginsession_user_id_fkey'), 'loginsession', type_='foreignkey')
    op.create_foreign_key(None, 'loginsession', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('roleuserlink_user_id_fkey'), 'roleuserlink', type_='foreignkey')
    op.create_foreign_key(None, 'roleuserlink', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roleuserlink', type_='foreignkey')
    op.create_foreign_key(op.f('roleuserlink_user_id_fkey'), 'roleuserlink', 'userbase', ['user_id'], ['id'])
    op.drop_constraint(None, 'loginsession', type_='foreignkey')
    op.create_foreign_key(op.f('loginsession_user_id_fkey'), 'loginsession', 'userbase', ['user_id'], ['id'])
    op.add_column('comment', sa.Column('member_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('comment', sa.Column('poster_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_poster_id_fkey'), 'comment', 'poster', ['poster_id'], ['id'])
    op.create_foreign_key(op.f('comment_member_id_fkey'), 'comment', 'member', ['member_id'], ['id'])
    op.drop_column('comment', 'post_id')
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'parend_id')
    op.drop_column('comment', 'created_at')
    op.drop_column('comment', 'content')
    op.drop_constraint(None, 'authsession', type_='foreignkey')
    op.create_foreign_key(op.f('authsession_user_id_fkey'), 'authsession', 'userbase', ['user_id'], ['id'])
    op.create_table('member',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('base_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['userbase.id'], name=op.f('member_base_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('member_pkey')),
    sa.UniqueConstraint('base_id', name=op.f('member_base_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('userbase',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='userbase_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('poster',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('base_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['userbase.id'], name=op.f('poster_base_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('poster_pkey')),
    sa.UniqueConstraint('base_id', name=op.f('poster_base_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('posttaglink')
    op.drop_table('post')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
