"""Add in_newsletter field to user

Revision ID: 6ec406df53d6
Revises: 85c61c06f5da
Create Date: 2025-08-20 19:30:20.505468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ec406df53d6'
down_revision: Union[str, None] = '85c61c06f5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('in_newsletter', sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'in_newsletter')
    # ### end Alembic commands ###
