"""empty message

Revision ID: 6ed76692a88a
Revises: 8ab4c6132c8d
Create Date: 2025-06-03 00:46:01.846316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ed76692a88a'
down_revision: Union[str, None] = '8ab4c6132c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileresource', sa.Column('id', sa.Uuid(), nullable=False))
    op.drop_column('fileresource', 'resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fileresource', sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('fileresource', 'id')
    # ### end Alembic commands ###
