"""empty message

Revision ID: 7a5252575767
Revises: 1a339a7f1777
Create Date: 2025-06-18 23:15:50.186045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a5252575767'
down_revision: Union[str, None] = '1a339a7f1777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('banned', sa.Boolean(), server_default="false", nullable=False))
    op.add_column('user', sa.Column('last_ban_motive', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_ban_motive')
    op.drop_column('user', 'banned')
    # ### end Alembic commands ###
