"""empty message

Revision ID: 833ce90bcb5d
Revises: 6ed76692a88a
Create Date: 2025-06-03 17:30:26.091440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '833ce90bcb5d'
down_revision: Union[str, None] = '6ed76692a88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('featured', sa.Boolean(),server_default="false", nullable=False))
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('post', 'description',
               existing_type=sa.VARCHAR(length=400),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'description',
               existing_type=sa.VARCHAR(length=400),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('post', 'featured')
    # ### end Alembic commands ###
