"""empty message

Revision ID: 8ab4c6132c8d
Revises: eeb33bf613f7
Create Date: 2025-06-02 20:17:15.991175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ab4c6132c8d'
down_revision: Union[str, None] = 'eeb33bf613f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpostlikelink',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('usercommentlikelink',
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.add_column('comment', sa.Column('likes', sa.Integer(),server_default="0", nullable=False))
    op.add_column('comment', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('comment_parend_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    op.drop_column('comment', 'parend_id')
    op.add_column('post', sa.Column('likes', sa.Integer(),server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'likes')
    op.add_column('comment', sa.Column('parend_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_parend_id_fkey'), 'comment', 'comment', ['parend_id'], ['id'])
    op.drop_column('comment', 'parent_id')
    op.drop_column('comment', 'likes')
    op.drop_table('usercommentlikelink')
    op.drop_table('userpostlikelink')
    # ### end Alembic commands ###
