"""empty message

Revision ID: ceb74fc9666d
Revises: 951de6b4897b
Create Date: 2025-06-01 17:39:03.151373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ceb74fc9666d'
down_revision: Union[str, None] = '951de6b4897b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cover', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'cover')
    # ### end Alembic commands ###
