"""empty message

Revision ID: cf2c2a77d5d3
Revises: c864ee50e431
Create Date: 2025-05-31 16:02:01.444496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf2c2a77d5d3'
down_revision: Union[str, None] = 'c864ee50e431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'level')
    # ### end Alembic commands ###
