"""empty message

Revision ID: d78b8dd9875f
Revises: cf2c2a77d5d3
Create Date: 2025-05-31 19:37:52.877599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd78b8dd9875f'
down_revision: Union[str, None] = 'cf2c2a77d5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=100), server_default="", nullable=True))
    op.add_column('post', sa.Column('description', sa.String(length=400), server_default="", nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'description')
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
