"""empty message

Revision ID: f2a695d128e1
Revises: a893d386856b
Create Date: 2025-06-14 10:54:10.799794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2a695d128e1'
down_revision: Union[str, None] = 'a893d386856b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewaction', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('visitaction', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('visitaction', 'id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitaction', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('visitaction', 'created_at')
    op.drop_column('viewaction', 'created_at')
    # ### end Alembic commands ###
